library("ggplot2")
library("ggrepel")
table <- read.csv("mds.mds", sep="\t", header=TRUE)
pca_plot <- ggplot(table, aes(table$C1,table$C2), fill="red") + geom_point(size=2) + geom_text_repel(aes(label=table$FID)) + xlab("Dimension 1") + ylab("Dimension 2")
ggsave("mds.pdf", pca_plot, dpi=300, height=7, width=7)